version: '3.5'

services:
  ws:
    image: chaos-jenkins-test:1.0.0
    user: "$_UID:$GID"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://navitia:navitia@172.18.0.1/chaos
      - RABBITMQ_CONNECTION_STRING=pyamqp://guest:guest@172.18.0.1:5672//?heartbeat=60
      - NAVITIA_URL=http://api.navitia.io
      - DOMAIN_NAME=chaos-ws.local.canaltp.fr
      - CACHE_TYPE=redis
      - CACHE_REDIS_HOST=redis
      - NAVITIA_CACHE_TIMEOUT=86400
      - NAVITIA_PUBDATE_CACHE_TIMEOUT=10
    volumes:
      - .:/var/www/Chaos

  redis:
    image: redis

networks:
  default:
    external:
      name: canaltp
