version: '3'

services:
  ws:
    image: chaos-prod:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_ENABLED=0
      - NAVITIA_URL=http://navitia2-ws.ctp.internal.canaltp.fr
      - SQLALCHEMY_DATABASE_URI=postgresql://navitia:navitia@172.18.0.1/chaos
    volumes:
      - .:/var/www/Chaos
    working_dir: /var/www/Chaos

networks:
  default:
    external:
      name: canaltp
