version: '3.5'

services:
  ws:
    image: navitia/chaos-ws:dev
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - RABBITMQ_CONNECTION_STRING=pyamqp://guest:guest@172.21.0.1:5672//?heartbeat=60
      - SQLALCHEMY_DATABASE_URI=postgresql://navitia:navitia@172.21.0.1/chaos
    volumes:
      - .:/srv/chaos
    working_dir: /srv/chaos

networks:
  default:
    external:
      name: canaltp
