version: '3'

services:
  ws:
    image: chaos-prod:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_ENABLED=0
      - NAVITIA_URL=http://navitia2-ws.ctp.internal.canaltp.fr
      - SQLALCHEMY_DATABASE_URI=postgresql://navitia:navitia@database/chaos_testing
    volumes:
      - .:/var/www/Chaos
    working_dir: /var/www/Chaos
    links:
      - database

  database:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=navitia
      - POSTGRES_PASSWORD=navitia
      - POSTGRES_DB=chaos_testing
    volumes:
      - ./docker/postgres/add_uuid_extension.sh:/docker-entrypoint-initdb.d/add_uuid_extension.sh

networks:
  default:
    external:
      name: canaltp
