database:
  build: postgresql/.
  container_name: "chaos_database"
  environment:
    - PGPASSWORD=%~\`4cj,|@snhg!''f@ay~
    - POSTGRES_PASS=%~\`4cj,|@snhg!''f@ay~
    - NAVITIA_PASSWORD=AGPXSnTFHmXknK
  net: "host"
  ports:
   - 5432:5432
  volumes:
   - logs:/var/log/postgresql
   - data:/var/lib/postgresql
web:
  build: app/.
  container_name: "chaos"
  environment:
   - PGPASSWORD=AGPXSnTFHmXknK
  net: "host"
  ports:
   - 5000:5000
  volumes:
   - ..:/var/www/chaos

