---
swagger: '2.0'

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: v1
  title: Documentation of API Chaos
  description: |
    Chaos is the web service which can feed [Navitia](https://github.com/CanalTP/navitia) with real-time [disruptions](http://doc.navitia.io/#traffic-reports).

    It can work together with [Kirin](https://github.com/CanalTP/kirin) which can feed [Navitia](https://github.com/CanalTP/navitia) with real-time delays.

    Chaos manage disruptions and help you to communicate with your travellers on the best.

    ** Requirements **

    Before using Chaos, you will need few things:
     * a Navitia token, allowing you to request navitia on a data coverage
     * a customer ID
     * a contributor ID

    Your usual Kisio Digital interlocutor can provide you these elements, and an access to the production or pre-production platform.
    Before using the API in production, you will need to provide:
     * integration specifications
     * expected load your application will generate.

    These two points are recquired to help us managing the Chaos platform.
  license:
    name: AGPL
    url: "http://www.gnu.org/licenses/agpl-3.0.html"

################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
host: 127.0.0.1:5000
basePath: /
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json

################################################################################
#                                   Tags                                       #
################################################################################
tags:
  - name: Severity
  - name: Category

paths:
  /severities:
    get:
      description: Retrieves all the severities ordered by priority
      parameters:
      - $ref: "#/parameters/header_authorization"
      - $ref: "#/parameters/header_coverage"
      - $ref: "#/parameters/header_customer_id"
      - $ref: "#/parameters/header_contributors"
      tags:
        - Severity
      responses:
        200:
          description: List of severities
          schema:
            type: object
            properties:
              meta:
                type: object
              severities:
                type: array
                items:
                  $ref: "#/definitions/severity"
    post:
      description: Creates a severity
      consumes:
        - application/json
      parameters:
      - $ref: "#/parameters/header_authorization"
      - $ref: "#/parameters/header_coverage"
      - $ref: "#/parameters/header_customer_id"
      - $ref: "#/parameters/header_contributors"
      - in: body
        name: body
        description: Severity that needs to be stored
        schema:
          $ref: "#/definitions/severity_creation"
      tags:
        - Severity
      responses:
        201:
          description: Created severity
          schema:
            type: object
            properties:
              severity:
                $ref: "#/definitions/severity"
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              severity:
                $ref: "#/definitions/severity_error_required_property"
  /severities/{id}:
    get:
      description: Retrieve the severity identified by ID
      parameters:
      - $ref: "#/parameters/header_authorization"
      - $ref: "#/parameters/header_coverage"
      - $ref: "#/parameters/header_customer_id"
      - $ref: "#/parameters/header_contributors"
      - $ref: "#/parameters/entity_id"
      tags:
        - Severity
      responses:
        200:
          description: Severity entity
          schema:
            type: object
            properties:
              severity:
                $ref: "#/definitions/severity"
    put:
      description: Update a severity
      parameters:
      - $ref: "#/parameters/header_authorization"
      - $ref: "#/parameters/header_coverage"
      - $ref: "#/parameters/header_customer_id"
      - $ref: "#/parameters/header_contributors"
      - $ref: "#/parameters/entity_id"
      tags:
        - Severity
      responses:
        200:
          description: Severity entity
          schema:
            type: object
            properties:
              severity:
                $ref: "#/definitions/severity"
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              severity:
                $ref: "#/definitions/severity_error_required_property"
    delete:
      description: remove a severity
      parameters:
      - $ref: "#/parameters/header_authorization"
      - $ref: "#/parameters/header_coverage"
      - $ref: "#/parameters/header_customer_id"
      - $ref: "#/parameters/header_contributors"
      - $ref: "#/parameters/entity_id"
      tags:
        - Severity
      responses:
        204:
          description: Severity has been removed
        400:
          description: BAD REQUEST
          schema:
            type: object
            properties:
              error:
                $ref: "#/definitions/bad_id"

  /categories:
    get:
      description: Retrieve the list of all categories
      parameters:
      - $ref: "#/parameters/header_authorization"
      - $ref: "#/parameters/header_coverage"
      - $ref: "#/parameters/header_customer_id"
      - $ref: "#/parameters/header_contributors"
      tags:
        - Category
      responses:
        200:
          description: List of categories
          schema:
            type: object
            properties:
              meta:
                type: object
              severities:
              categories:
                type: array
                items:
                  $ref: "#/definitions/category"


################################################################################
#                                 Parameters                                  #
################################################################################
parameters:
  header_customer_id:
    in: header
    required: true
    type: string
    description: Client code. A client is owner of cause, channel, severity and tag
    name: X-Customer-Id
  header_coverage:
    in: header
    required: true
    type: string
    description: Coverage of navitia services
    name: X-Coverage
  header_authorization:
    in: header
    required: true
    type: string
    description: Token for navitia services
    name: Authorization
  header_contributors:
    required: true
    type: string
    description: Contributor code. A contributor is owner of a disruption
    name: X-Contributors
    in: header
  entity_id:
    required: true
    type: string
    description: Entity identifier
    name: id
    in: path

################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  bad_id:
    type: "object"
    properties:
      message:
        type: "string"
  href:
    type: "object"
    properties:
      href:
        type: "string"
  wording:
    type: "object"
    properties:
      key:
        type: "string"
      value:
        type: "string"
  severity:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      self:
        type: "object"
        $ref: "#/definitions/href"
      color:
        type: "string"
      created_at:
        type: "string"
        format: "date-time"
      effect:
        type: "string"
      priority:
        type: "integer"
      updated_at:
        type: "string"
        format: "date-time"
      wording:
        type: "string"
      wordings:
        type: "array"
        items:
          $ref: "#/definitions/wording"
  severity_creation:
    type: "object"
    properties:
      color:
        type: "string"
      effect:
        type: "string"
      priority:
        type: "integer"
      wordings:
        type: "array"
        items:
          $ref: "#/definitions/wording"
  severity_error_required_property:
    type: "object"
    properties:
      error:
        type: "object"
        properties:
          message :
            type: "string"
  category:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      self:
        type: "object"
        $ref: "#/definitions/href"
      name:
        type: "string"
      created_at:
        type: "string"
        format: "date-time"
      updated_at:
        type: "string"
        format: "date-time"